services:
  catgpt:
    build: .
    ports:
      - "7861:7860"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - YOLO_CONFIG_DIR=/app/.config/Ultralytics
      - HOME=/app
    volumes:
      - ./yolo_outputs:/app/yolo_outputs
      - ultralytics_config:/app/.config/Ultralytics
      - /dev:/dev  # Mount all devices
    privileged: true  # Required for camera access
    restart: unless-stopped
    networks:
      - catgpt-network

networks:
  catgpt-network:
    driver: bridge

volumes:
  ultralytics_config: